name: Broadcaster
version: @VERSION@
main: de.axelrindle.broadcaster.Broadcaster
author: Axel Rindle
website: http://dev.bukkit.org/bukkit-plugins/Broadcaster-Plugin
depend: [PocketKnife]
api-version: 1.15
commands:
  brc:
    description: Control's the Plugin
    usage: /brc
