name: Broadcaster
version: 2.1.0
main: de.axelrindle.broadcaster.Broadcaster
author: Axel Rindle (lalo5)
website: http://dev.bukkit.org/bukkit-plugins/Broadcaster-Plugin
commands:
  brc:
    description: Control's the Plugin
    usage: /brc
