name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test: # TODO: Split into build & test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        jdk: ['8', '11', '15'] # https://github.com/marketplace/actions/setup-java-jdk#supported-version-syntax
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v2
      with:
        distribution: 'adopt'
        java-version: ${{ matrix.jdk }}
    - name: Build project
      run: ./gradlew build -x test
    - name: Run tests
      run: ./gradlew test
    - name: Run codacy-coverage-reporter
      uses: codacy/codacy-coverage-reporter-action@master
      with:
        project-token: ${{ secrets.CODACY_PROJECT_TOKEN }}
    - uses: actions/upload-artifact@v2
      with:
        name: Test Reports
        path: build/reports
